-- Sussex Barber Shop — Postgres schema (Neon)
--
-- Replaces nine Google Sheets. Run once against a fresh database:
--   psql "$DATABASE_URL" -f db/schema.sql
-- Safe to re-run: every statement is IF NOT EXISTS or CREATE OR REPLACE.
--
-- Two things the Sheet could not do, and the reason half the old backend
-- existed:
--
--   Types.  A Sheet hands back a Date for a cell reading "10:00", a string for
--           the same cell in another row, and #ERROR! for a phone number that
--           begins with a plus. Three separate repair functions existed to
--           patch that up. A TIME column is a time, and text is text.
--
--   Rules.  Double-booking was held off by a ten-second lock around a read and
--           a write. Here it is a unique index: two requests can arrive in the
--           same millisecond and the second one is refused by the database.

-- ---------------------------------------------------------------------------
-- Staff
-- ---------------------------------------------------------------------------

-- Rotas and time off hang off a barber's id, not their name. Renaming someone
-- in the panel used to strand every rota row keyed to the old spelling.
CREATE TABLE IF NOT EXISTS barbers (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text    NOT NULL UNIQUE,
    image_url   text    NOT NULL DEFAULT '',
    -- The order the cards appear in on the booking form.
    position    integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- One row per barber per weekday. weekday follows ISO: 1 = Monday, 7 = Sunday.
-- The Sheet stored the English day name and matched it by string, which meant
-- a stray space or a different spelling silently took a barber off the rota.
CREATE TABLE IF NOT EXISTS barber_hours (
    barber_id   integer NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
    weekday     smallint NOT NULL CHECK (weekday BETWEEN 1 AND 7),
    working     boolean NOT NULL DEFAULT false,
    starts_at   time,
    ends_at     time,
    break_start time,
    break_end   time,
    PRIMARY KEY (barber_id, weekday),
    -- A working day needs hours, and they have to run forwards.
    CONSTRAINT barber_hours_span CHECK (
        NOT working OR (starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at)
    ),
    CONSTRAINT barber_hours_break CHECK (
        break_start IS NULL OR break_end IS NULL OR break_start < break_end
    )
);

-- Holidays and sick days. A single-day absence is the common case, so the two
-- dates are allowed to be equal.
CREATE TABLE IF NOT EXISTS time_off (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id   integer NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
    starts_on   date NOT NULL,
    ends_on     date NOT NULL,
    note        text NOT NULL DEFAULT '',
    CONSTRAINT time_off_span CHECK (starts_on <= ends_on)
);

CREATE INDEX IF NOT EXISTS time_off_lookup ON time_off (barber_id, starts_on, ends_on);

-- ---------------------------------------------------------------------------
-- What the shop sells and when it opens
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS services (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en       text    NOT NULL,
    name_nl       text    NOT NULL DEFAULT '',
    -- Money is never a float. 28.00, not 28.000000000000004.
    price         numeric(6,2) NOT NULL CHECK (price >= 0),
    duration_min  integer NOT NULL DEFAULT 30 CHECK (duration_min > 0),
    position      integer NOT NULL DEFAULT 0
);

-- Shop opening hours, one row per weekday.
CREATE TABLE IF NOT EXISTS shop_hours (
    weekday     smallint PRIMARY KEY CHECK (weekday BETWEEN 1 AND 7),
    is_open     boolean NOT NULL DEFAULT true,
    opens_at    time,
    closes_at   time,
    CONSTRAINT shop_hours_span CHECK (
        NOT is_open OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)
    )
);

-- ---------------------------------------------------------------------------
-- Site content the panel edits
-- ---------------------------------------------------------------------------

-- Free text: hero copy, address, phone, Instagram and map links, visit count.
CREATE TABLE IF NOT EXISTS settings (
    key    text PRIMARY KEY,
    value  text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gallery (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url text    NOT NULL,
    position  integer NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Who keeps coming back
-- ---------------------------------------------------------------------------

-- One row per person, keyed on their phone number.
--
-- The shop already identifies people by phone: it is what "Already booked?"
-- searches on, what the one-booking-per-slot rules count, and the only thing
-- every customer gives — the email field is optional and most leave it empty.
-- So the identity is the number, not an account: nobody signs up, nobody has a
-- password, and nothing is asked for that was not already being typed.
--
-- phone_key is the last nine digits, the same normalisation bookings use, so
-- "06 1234 5678", "+31 6 1234 5678" and "0031612345678" are one customer.
--
-- What this is for: a discount, a promo code, a loyalty count or a gift card
-- all need somewhere to hang, and "the tenth cut is free" is a question about
-- a person rather than a booking. That question has no answer while the diary
-- is the only record — you can count rows with the same number, but you cannot
-- attach anything to the person. This table is that missing half. None of
-- those features exist yet; when one does, it references customers(id) and
-- needs no change here.
CREATE TABLE IF NOT EXISTS customers (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_key   text NOT NULL UNIQUE,
    -- The most recent spelling of the name and address they gave. Not a
    -- history: the diary keeps what was typed for each booking, and this is
    -- only so the panel can show who a customer is without reading the diary.
    name        text NOT NULL DEFAULT '',
    email       text NOT NULL DEFAULT '',
    -- Free text for the shop. "Prefers Amir", "allergic to the blue gel".
    -- Never shown to the customer.
    note        text NOT NULL DEFAULT '',
    first_seen  timestamptz NOT NULL DEFAULT now(),
    last_seen   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- The diary
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bookings (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booked_on     date NOT NULL,
    booked_at     time NOT NULL,
    service       text NOT NULL,
    -- Kept by name and not by id on purpose: the diary is a record of what
    -- happened. Deleting a barber must not erase the appointments they worked,
    -- and renaming one must not rewrite last year's bookings.
    barber        text NOT NULL DEFAULT '',
    customer_name text NOT NULL,
    phone         text NOT NULL,
    email         text NOT NULL DEFAULT '',
    price         numeric(6,2),
    status        text NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'cancelled')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    cancelled_at  timestamptz,
    -- Who wrote this row down: 'web' is the booking form, 'shop' is somebody
    -- in the panel taking a booking over the phone or at the counter. The
    -- diary is a record of what happened, and "the customer typed this" and
    -- "we typed this for them" are different facts — a wrong number in the
    -- second one is our mistake to chase, not theirs.
    -- No CHECK on it, deliberately: the same column is added by ALTER at the
    -- foot of this file for databases that predate it, and Postgres has no
    -- ADD CONSTRAINT IF NOT EXISTS — so a check here would exist on a fresh
    -- database and not on the shop's, which is worse than not having one. The
    -- API is the only writer and it writes one of two literals.
    source        text NOT NULL DEFAULT 'web',
    -- Which language the booking was made in, so every email that follows
    -- arrives in the one the customer was reading. Most of this shop's
    -- customers are Dutch; the site's default is English, and a confirmation
    -- in the wrong language is the first thing they see of us in writing.
    lang          text NOT NULL DEFAULT 'en',
    -- When the morning reminder went out, and when the review was asked for.
    -- Timestamps rather than flags so a duplicate is impossible: the daily job
    -- selects on IS NULL, and a job that runs twice sends nothing the second
    -- time. A boolean would have needed the same query anyway and told us
    -- nothing about when.
    reminded_at   timestamptz,
    review_asked_at timestamptz,
    -- Which customer this is, once there is a row for them.
    --
    -- Nullable, and ON DELETE SET NULL rather than CASCADE. The diary is a
    -- record of what happened: removing a customer must not remove the
    -- appointments they came to, any more than removing a barber does. The
    -- booking keeps its own name and number either way, so a row with no
    -- customer is still a complete record of that appointment.
    customer_id   integer REFERENCES customers(id) ON DELETE SET NULL,
    -- Last nine digits of the phone number, so the Dutch local and
    -- international forms of one number match. Generated by the database
    -- rather than by the caller: normalisePhone() lived in three files and
    -- they had to agree.
    phone_key     text GENERATED ALWAYS AS (
                      right(regexp_replace(phone, '\D', '', 'g'), 9)
                  ) STORED,
    CONSTRAINT bookings_cancelled_has_time CHECK (
        (status = 'cancelled') = (cancelled_at IS NOT NULL)
    )
);

-- The rule the ten-second lock was standing in for. One named barber cannot
-- hold two appointments at the same moment, and the database enforces it no
-- matter how many requests arrive at once.
--
-- Bookings with no preference are excluded: they do not name a chair, so how
-- many fit is a question of how many barbers are rostered, which the API
-- answers. A unique index cannot count.
CREATE UNIQUE INDEX IF NOT EXISTS bookings_one_chair
    ON bookings (booked_on, booked_at, barber)
    WHERE status = 'active' AND barber <> '';

-- Availability for a date, the busiest query on the site.
CREATE INDEX IF NOT EXISTS bookings_by_day
    ON bookings (booked_on, booked_at)
    WHERE status = 'active';

-- "Already booked?" — a customer finding their own appointments.
CREATE INDEX IF NOT EXISTS bookings_by_phone
    ON bookings (phone_key, booked_on)
    WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- How often one address may use the endpoints that need no password
-- ---------------------------------------------------------------------------

-- The way to damage a barber shop's diary is not to break into it. It is to
-- book it: the form is public and meant to be, and a script typing a different
-- phone number each time walks straight past the per-customer cap and fills
-- next week.
--
-- Counted here rather than in the function's memory, because a fleet of
-- serverless functions each start from zero and a count that resets on every
-- cold start is not a count.
CREATE TABLE IF NOT EXISTS rate_limit (
    bucket    text NOT NULL,          -- 'addBooking:h:1.2.3.4'
    window_at timestamptz NOT NULL,   -- the start of the window it counts
    hits      integer NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket, window_at)
);

-- Only ever read by the daily sweep, which throws away windows that have
-- passed. Nothing else looks at a row twice.
CREATE INDEX IF NOT EXISTS rate_limit_sweep ON rate_limit (window_at);

-- ---------------------------------------------------------------------------
-- When each round of the reminder last ran
-- ---------------------------------------------------------------------------

-- One row per job, forever. This is a timestamp, not a log.
--
-- It exists so the reminders have a second clock. The first is a GitHub
-- Actions schedule, and GitHub disables a scheduled workflow in a repository
-- with no activity for sixty days — a barber shop that is running well never
-- pushes code, so that day was always coming. Now an ordinary visitor's
-- request checks this timestamp, and sets the round off itself if it has gone
-- stale. See standInForTheClock() in api/index.js.
--
-- The claim is one conditional UPDATE (claimJobRun() in api/_lib/db.js) rather
-- than a read followed by a write, so ten requests landing together produce
-- one round between them instead of ten. Reading the time and then writing it
-- would let all ten through, and ten rounds at once is ten chances of a
-- customer getting the same reminder twice.
CREATE TABLE IF NOT EXISTS job_runs (
    job    text PRIMARY KEY,          -- 'soon'
    ran_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Columns added after the table already existed
-- ---------------------------------------------------------------------------
--
-- CREATE TABLE IF NOT EXISTS does nothing at all to a table that is already
-- there — including adding a column to it. A database created before these
-- three existed would silently keep the old shape, and the first thing anyone
-- would know about it is the panel failing to list the diary.
--
-- So they are stated twice: in the table above for a fresh database, and here
-- for one that is already running. ADD COLUMN IF NOT EXISTS is a no-op the
-- second time. The API also runs these itself the first time it needs one of
-- them, so forgetting to run this file is not how the shop finds out.
-- Whether a barber has a card in "Our Master Barbers" on the website.
--
-- Not whether they can be booked: the two are different questions and the shop
-- asked for one of them. Somebody who has not had their photograph taken yet,
-- or who covers two days a week, still takes appointments — they just do not
-- need a card introducing them.
--
-- Defaults to true, so switching this on changes nothing until the shop turns
-- somebody off deliberately.
ALTER TABLE barbers ADD COLUMN IF NOT EXISTS on_team boolean NOT NULL DEFAULT true;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'web';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS lang text NOT NULL DEFAULT 'en';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS reminded_at timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS review_asked_at timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_id integer;

-- The foreign key is added separately and only if it is not already there.
-- Postgres has no ADD CONSTRAINT IF NOT EXISTS, and running this file twice
-- has to stay harmless.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bookings_customer_fk') THEN
        ALTER TABLE bookings
            ADD CONSTRAINT bookings_customer_fk
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Every number already in the diary becomes a customer, and every booking is
-- pointed at its own. Written so it can be re-run: ON CONFLICT skips the ones
-- that exist, and the update only touches rows that have no customer yet.
INSERT INTO customers (phone_key, name, email, first_seen, last_seen)
SELECT phone_key,
       (array_agg(customer_name ORDER BY created_at DESC))[1],
       COALESCE((array_agg(NULLIF(email, '') ORDER BY created_at DESC))[1], ''),
       min(created_at), max(created_at)
  FROM bookings
 WHERE phone_key <> ''
 GROUP BY phone_key
ON CONFLICT (phone_key) DO NOTHING;

UPDATE bookings b SET customer_id = c.id
  FROM customers c
 WHERE b.customer_id IS NULL AND b.phone_key = c.phone_key;

CREATE INDEX IF NOT EXISTS bookings_by_customer ON bookings (customer_id);
