-- Sussex Barber Shop — Postgres schema (Neon)
--
-- Replaces nine Google Sheets. Run once against a fresh database:
--   psql "$DATABASE_URL" -f db/schema.sql
-- Safe to re-run: every statement is IF NOT EXISTS or CREATE OR REPLACE.
--
-- Two things the Sheet could not do, and the reason half the old backend
-- existed:
--
--   Types.  A Sheet hands back a Date for a cell reading "10:00", a string for
--           the same cell in another row, and #ERROR! for a phone number that
--           begins with a plus. Three separate repair functions existed to
--           patch that up. A TIME column is a time, and text is text.
--
--   Rules.  Double-booking was held off by a ten-second lock around a read and
--           a write. Here it is a unique index: two requests can arrive in the
--           same millisecond and the second one is refused by the database.

-- ---------------------------------------------------------------------------
-- Staff
-- ---------------------------------------------------------------------------

-- Rotas and time off hang off a barber's id, not their name. Renaming someone
-- in the panel used to strand every rota row keyed to the old spelling.
CREATE TABLE IF NOT EXISTS barbers (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text    NOT NULL UNIQUE,
    image_url   text    NOT NULL DEFAULT '',
    -- The order the cards appear in on the booking form.
    position    integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- One row per barber per weekday. weekday follows ISO: 1 = Monday, 7 = Sunday.
-- The Sheet stored the English day name and matched it by string, which meant
-- a stray space or a different spelling silently took a barber off the rota.
CREATE TABLE IF NOT EXISTS barber_hours (
    barber_id   integer NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
    weekday     smallint NOT NULL CHECK (weekday BETWEEN 1 AND 7),
    working     boolean NOT NULL DEFAULT false,
    starts_at   time,
    ends_at     time,
    break_start time,
    break_end   time,
    PRIMARY KEY (barber_id, weekday),
    -- A working day needs hours, and they have to run forwards.
    CONSTRAINT barber_hours_span CHECK (
        NOT working OR (starts_at IS NOT NULL AND ends_at IS NOT NULL AND starts_at < ends_at)
    ),
    CONSTRAINT barber_hours_break CHECK (
        break_start IS NULL OR break_end IS NULL OR break_start < break_end
    )
);

-- Holidays and sick days. A single-day absence is the common case, so the two
-- dates are allowed to be equal.
CREATE TABLE IF NOT EXISTS time_off (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id   integer NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
    starts_on   date NOT NULL,
    ends_on     date NOT NULL,
    note        text NOT NULL DEFAULT '',
    CONSTRAINT time_off_span CHECK (starts_on <= ends_on)
);

CREATE INDEX IF NOT EXISTS time_off_lookup ON time_off (barber_id, starts_on, ends_on);

-- ---------------------------------------------------------------------------
-- What the shop sells and when it opens
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS services (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en       text    NOT NULL,
    name_nl       text    NOT NULL DEFAULT '',
    -- Money is never a float. 28.00, not 28.000000000000004.
    price         numeric(6,2) NOT NULL CHECK (price >= 0),
    duration_min  integer NOT NULL DEFAULT 30 CHECK (duration_min > 0),
    position      integer NOT NULL DEFAULT 0
);

-- Shop opening hours, one row per weekday.
CREATE TABLE IF NOT EXISTS shop_hours (
    weekday     smallint PRIMARY KEY CHECK (weekday BETWEEN 1 AND 7),
    is_open     boolean NOT NULL DEFAULT true,
    opens_at    time,
    closes_at   time,
    CONSTRAINT shop_hours_span CHECK (
        NOT is_open OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)
    )
);

-- ---------------------------------------------------------------------------
-- Site content the panel edits
-- ---------------------------------------------------------------------------

-- Free text: hero copy, address, phone, Instagram and map links, visit count.
CREATE TABLE IF NOT EXISTS settings (
    key    text PRIMARY KEY,
    value  text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gallery (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url text    NOT NULL,
    position  integer NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- The diary
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bookings (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booked_on     date NOT NULL,
    booked_at     time NOT NULL,
    service       text NOT NULL,
    -- Kept by name and not by id on purpose: the diary is a record of what
    -- happened. Deleting a barber must not erase the appointments they worked,
    -- and renaming one must not rewrite last year's bookings.
    barber        text NOT NULL DEFAULT '',
    customer_name text NOT NULL,
    phone         text NOT NULL,
    email         text NOT NULL DEFAULT '',
    price         numeric(6,2),
    status        text NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'cancelled')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    cancelled_at  timestamptz,
    -- Who wrote this row down: 'web' is the booking form, 'shop' is somebody
    -- in the panel taking a booking over the phone or at the counter. The
    -- diary is a record of what happened, and "the customer typed this" and
    -- "we typed this for them" are different facts — a wrong number in the
    -- second one is our mistake to chase, not theirs.
    -- No CHECK on it, deliberately: the same column is added by ALTER at the
    -- foot of this file for databases that predate it, and Postgres has no
    -- ADD CONSTRAINT IF NOT EXISTS — so a check here would exist on a fresh
    -- database and not on the shop's, which is worse than not having one. The
    -- API is the only writer and it writes one of two literals.
    source        text NOT NULL DEFAULT 'web',
    -- Which language the booking was made in, so every email that follows
    -- arrives in the one the customer was reading. Most of this shop's
    -- customers are Dutch; the site's default is English, and a confirmation
    -- in the wrong language is the first thing they see of us in writing.
    lang          text NOT NULL DEFAULT 'en',
    -- When the morning reminder went out, and when the review was asked for.
    -- Timestamps rather than flags so a duplicate is impossible: the daily job
    -- selects on IS NULL, and a job that runs twice sends nothing the second
    -- time. A boolean would have needed the same query anyway and told us
    -- nothing about when.
    reminded_at   timestamptz,
    review_asked_at timestamptz,
    -- Last nine digits of the phone number, so the Dutch local and
    -- international forms of one number match. Generated by the database
    -- rather than by the caller: normalisePhone() lived in three files and
    -- they had to agree.
    phone_key     text GENERATED ALWAYS AS (
                      right(regexp_replace(phone, '\D', '', 'g'), 9)
                  ) STORED,
    CONSTRAINT bookings_cancelled_has_time CHECK (
        (status = 'cancelled') = (cancelled_at IS NOT NULL)
    )
);

-- The rule the ten-second lock was standing in for. One named barber cannot
-- hold two appointments at the same moment, and the database enforces it no
-- matter how many requests arrive at once.
--
-- Bookings with no preference are excluded: they do not name a chair, so how
-- many fit is a question of how many barbers are rostered, which the API
-- answers. A unique index cannot count.
CREATE UNIQUE INDEX IF NOT EXISTS bookings_one_chair
    ON bookings (booked_on, booked_at, barber)
    WHERE status = 'active' AND barber <> '';

-- Availability for a date, the busiest query on the site.
CREATE INDEX IF NOT EXISTS bookings_by_day
    ON bookings (booked_on, booked_at)
    WHERE status = 'active';

-- "Already booked?" — a customer finding their own appointments.
CREATE INDEX IF NOT EXISTS bookings_by_phone
    ON bookings (phone_key, booked_on)
    WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- How often one address may use the endpoints that need no password
-- ---------------------------------------------------------------------------

-- The way to damage a barber shop's diary is not to break into it. It is to
-- book it: the form is public and meant to be, and a script typing a different
-- phone number each time walks straight past the per-customer cap and fills
-- next week.
--
-- Counted here rather than in the function's memory, because a fleet of
-- serverless functions each start from zero and a count that resets on every
-- cold start is not a count.
CREATE TABLE IF NOT EXISTS rate_limit (
    bucket    text NOT NULL,          -- 'addBooking:h:1.2.3.4'
    window_at timestamptz NOT NULL,   -- the start of the window it counts
    hits      integer NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket, window_at)
);

-- Only ever read by the daily sweep, which throws away windows that have
-- passed. Nothing else looks at a row twice.
CREATE INDEX IF NOT EXISTS rate_limit_sweep ON rate_limit (window_at);

-- ---------------------------------------------------------------------------
-- Columns added after the table already existed
-- ---------------------------------------------------------------------------
--
-- CREATE TABLE IF NOT EXISTS does nothing at all to a table that is already
-- there — including adding a column to it. A database created before these
-- three existed would silently keep the old shape, and the first thing anyone
-- would know about it is the panel failing to list the diary.
--
-- So they are stated twice: in the table above for a fresh database, and here
-- for one that is already running. ADD COLUMN IF NOT EXISTS is a no-op the
-- second time. The API also runs these itself the first time it needs one of
-- them, so forgetting to run this file is not how the shop finds out.
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'web';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS lang text NOT NULL DEFAULT 'en';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS reminded_at timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS review_asked_at timestamptz;
